name: Test

on: [ push ]

jobs:
  test:
    #где запускаем
    runs-on: ubuntu-latest
    # что делаем
    steps:
      #выкачиваем репозиторий
      - uses: actions/checkout@v4
      # настраиваем java
      - uses: actions/setup-java@v4
        with:
          distribution: 'oracle' # кто поставляет java орокал или майкросовт и тд
          java-version: '21'
      - uses: Xotabu4/selenoid-github-action@v2
      # запускаем тесты             # тут с сайта selenide webdriver подключаем
      - run: ./gradlew clean test -Dselenide.remote=http://localhost:4444/wd/hub

